### ISSUE TITLE
Issue with function "handleOnKeyPress"

### ISSUE THREAD

**Issue by thatBrian** [NormanColoma/suggestion-react-search-input#9]
When the search bar is empty, clicking on the arrow keys throws an error. 
![image](https://user-images.githubusercontent.com/23340764/67110838-a57d6d00-f1a1-11e9-88e0-cb661c86d446.png)

**Comment by NormanColoma** [comment]
Thank you for the feedback. I'll fix it asap.

**Comment by NormanColoma** [comment]
Fixed in version 1.4.0
